version: 1.0.{build}

image:
- Ubuntu2004
- Visual Studio 2022
- macos

init:
- sh: if [[ "$OSTYPE" == "linux-gnu"* ]]; then (sudo apt update && sudo apt install -y xorg-dev mesa-common-dev libgl-dev libpulse-dev) fi

build_script:
- sh: git submodule init && git submodule update && cd ThirdParty/Oneiro/ && git submodule init && git submodule update && cd ../../ && mkdir build && cd build/ && cmake .. -DCMAKE_CXX23_EXTENSION_COMPILE_OPTION="-std=gnu++2a" && make
- cmd: git submodule init && git submodule update && cd ThirdParty/Oneiro/ && git submodule init && git submodule update && cd ../../ && mkdir build && cd build/ && cmake .. && cmake --build .
